### ISSUE TITLE
Support ANSI color codes

### ISSUE THREAD

**Issue by sunshowers** [oxidecomputer/buildomat#40] opened 2023-11-03 23:22 UTC
One of the neat things about GitHub Actions output is that it supports ANSI color codes. This makes the output easier to parse for commands that support it (e.g. cargo, nextest, etc).

It would be really nice if buildomat supported ANSI color codes as well.

**Comment by jclulow** [comment] 2023-11-04 00:35
I suspect this is a duplicate of #34!

**Closed** 2023-11-04 00:35 UTC

**Comment by sunshowers** [comment] 2023-11-04 01:03
It is! I searched for ANSI but not terminal, haha
